Repository devvsakib/power-the-web, pull requests merged in 2022-10, with the labels that each got.

#5 Feature : Add a readme file [fixes #3]
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#15 Update ProjectIdeas.txt
  PROJECTS/ProjectIdeas.txt
Labels: hacktoberfest

#16 React Counter App
  PROJECTS/React Counter App/.gitignore
  PROJECTS/React Counter App/README.md
  PROJECTS/React Counter App/package-lock.json
  PROJECTS/React Counter App/package.json
  PROJECTS/React Counter App/public/favicon.ico
  PROJECTS/React Counter App/public/index.html
  PROJECTS/React Counter App/public/logo192.png
  PROJECTS/React Counter App/public/logo512.png
  PROJECTS/React Counter App/public/manifest.json
  PROJECTS/React Counter App/public/robots.txt
  PROJECTS/React Counter App/src/App.jsx
  PROJECTS/React Counter App/src/App.test.js
  PROJECTS/React Counter App/src/components/counter/counter.jsx
  PROJECTS/React Counter App/src/index.css
  PROJECTS/React Counter App/src/index.jsx
  PROJECTS/React Counter App/src/logo.svg
  PROJECTS/React Counter App/src/reportWebVitals.js
  PROJECTS/React Counter App/src/setupTests.js
Labels: hacktoberfest, hacktoberfest-accepted

#17 React Calculator Added
  PROJECTS/React Calculator/.github/CODE_OF_CONDUCT.md
  PROJECTS/React Calculator/.github/CONTRIBUTING.md
  PROJECTS/React Calculator/.github/ISSUE_TEMPLATE/bug_report.md
  PROJECTS/React Calculator/.github/ISSUE_TEMPLATE/feature_request.md
  PROJECTS/React Calculator/.github/dependabot.yml
  PROJECTS/React Calculator/.gitignore
  PROJECTS/React Calculator/LICENSE
  PROJECTS/React Calculator/README.md
  PROJECTS/React Calculator/package.json
  PROJECTS/React Calculator/public/favicon.ico
  PROJECTS/React Calculator/public/index.html
  PROJECTS/React Calculator/public/logo192.png
  PROJECTS/React Calculator/public/logo512.png
  PROJECTS/React Calculator/public/manifest.json
  PROJECTS/React Calculator/public/reactCalci1.png
  PROJECTS/React Calculator/public/reactCalci2.png
  PROJECTS/React Calculator/public/robots.txt
  PROJECTS/React Calculator/src/components/App.js
  PROJECTS/React Calculator/src/components/Button.js
  PROJECTS/React Calculator/src/components/ButtonGroup.js
  PROJECTS/React Calculator/src/components/ButtonList.js
  PROJECTS/React Calculator/src/components/Footer.js
  PROJECTS/React Calculator/src/components/Header.js
  PROJECTS/React Calculator/src/components/Screen.js
  PROJECTS/React Calculator/src/components/styles/App.css
  PROJECTS/React Calculator/src/components/styles/Button.css
  PROJECTS/React Calculator/src/components/styles/Screen.css
  PROJECTS/React Calculator/src/fonts/pocket_calcuatlor_tt.ttf
  PROJECTS/React Calculator/src/index.css
  PROJECTS/React Calculator/src/index.js
  PROJECTS/React Calculator/yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#24 Real Time Chat
  PROJECTS/RealTimeChat/backend/.babelrc
  PROJECTS/RealTimeChat/backend/.editorconfig
  PROJECTS/RealTimeChat/backend/.env.example
  PROJECTS/RealTimeChat/backend/.eslintignore
  PROJECTS/RealTimeChat/backend/.eslintrc.js
  PROJECTS/RealTimeChat/backend/.gitignore
  PROJECTS/RealTimeChat/backend/.prettierignore
  PROJECTS/RealTimeChat/backend/.prettierrc
  PROJECTS/RealTimeChat/backend/README.md
  PROJECTS/RealTimeChat/backend/jest.config.js
  PROJECTS/RealTimeChat/backend/nodemon.json
  PROJECTS/RealTimeChat/backend/package-lock.json
  PROJECTS/RealTimeChat/backend/package.json
  PROJECTS/RealTimeChat/backend/src/App.js
  PROJECTS/RealTimeChat/backend/src/Listeners/RoomMessageSend.js
  PROJECTS/RealTimeChat/backend/src/Listeners/index.js
  PROJECTS/RealTimeChat/backend/src/Middlewares/LogHttpRequest.js
  PROJECTS/RealTimeChat/backend/src/Routes/NoMatch.js
  PROJECTS/RealTimeChat/backend/src/Routes/__tests__/NoMatch.test.js
  PROJECTS/RealTimeChat/backend/src/Services/Messages.js
  PROJECTS/RealTimeChat/backend/src/Services/Users.js
  PROJECTS/RealTimeChat/backend/src/Utils/GetRootDirectory.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Format/RemoveError.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Format/RemoveHttp.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Format/RemoveInfo.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Format/RemoveWarn.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Format/__tests__/RemoveError.test.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Format/__tests__/RemoveHttp.test.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Format/__tests__/RemoveInfo.test.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Format/__tests__/RemoveWarn.test.js
  PROJECTS/RealTimeChat/backend/src/Utils/Logger/Logger.js
  PROJECTS/RealTimeChat/backend/src/index.js
  PROJECTS/RealTimeChat/frontend/.editorconfig
  PROJECTS/RealTimeChat/frontend/.eslintrc.js
  PROJECTS/RealTimeChat/frontend/.gitignore
  PROJECTS/RealTimeChat/frontend/.prettierrc
  PROJECTS/RealTimeChat/frontend/README.md
  PROJECTS/RealTimeChat/frontend/babel.config.js
  PROJECTS/RealTimeChat/frontend/index.html
  PROJECTS/RealTimeChat/frontend/jest.config.ts
  PROJECTS/RealTimeChat/frontend/jest.setup.ts
  PROJECTS/RealTimeChat/frontend/package-lock.json
  PROJECTS/RealTimeChat/frontend/package.json
  PROJECTS/RealTimeChat/frontend/public/favicon.ico
  PROJECTS/RealTimeChat/frontend/public/robots.txt
  PROJECTS/RealTimeChat/frontend/src/App.tsx
  PROJECTS/RealTimeChat/frontend/src/AppStyles.tsx
  PROJECTS/RealTimeChat/frontend/src/Components/Chat/Chat.tsx
  PROJECTS/RealTimeChat/frontend/src/Components/Chat/Styles.tsx
  PROJECTS/RealTimeChat/frontend/src/Components/Chat/Types.ts
  PROJECTS/RealTimeChat/frontend/src/Styles.tsx
  PROJECTS/RealTimeChat/frontend/src/env.d.ts
  PROJECTS/RealTimeChat/frontend/src/index.tsx
  PROJECTS/RealTimeChat/frontend/tsconfig.json
  PROJECTS/RealTimeChat/frontend/tsconfig.node.json
  PROJECTS/RealTimeChat/frontend/vite.config.ts
Labels: hacktoberfest, hacktoberfest-accepted

#35 converted main html website into react project using tailwind.css
  PROJECTS/main-website/.gitignore
  PROJECTS/main-website/README.md
  PROJECTS/main-website/package-lock.json
  PROJECTS/main-website/package.json
  PROJECTS/main-website/postcss.config.js
  PROJECTS/main-website/public/index.html
  PROJECTS/main-website/public/manifest.json
  PROJECTS/main-website/public/robots.txt
  PROJECTS/main-website/src/App.css
  PROJECTS/main-website/src/App.js
  PROJECTS/main-website/src/App.test.js
  PROJECTS/main-website/src/index.css
  PROJECTS/main-website/src/index.js
  PROJECTS/main-website/src/style.css
  PROJECTS/main-website/tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#53 Added the footer
  assets/css/style.css
  blog.html
  contributor.html
  index.html
  project.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#56 disney clone projects issues: #55
  PROJECTS/clone-disney/.gitignore
  PROJECTS/clone-disney/README.md
  PROJECTS/clone-disney/package-lock.json
  PROJECTS/clone-disney/package.json
  PROJECTS/clone-disney/public/favicon.ico
  PROJECTS/clone-disney/public/firebase.js
  PROJECTS/clone-disney/public/images/cta-logo-one.svg
  PROJECTS/clone-disney/public/images/cta-logo-two.png
  PROJECTS/clone-disney/public/images/favicon.svg
  PROJECTS/clone-disney/public/images/group-icon.png
  PROJECTS/clone-disney/public/images/home-background.png
  PROJECTS/clone-disney/public/images/home-icon.svg
  PROJECTS/clone-disney/public/images/login-background.jpg
  PROJECTS/clone-disney/public/images/logo.svg
  PROJECTS/clone-disney/public/images/movie-icon.svg
  PROJECTS/clone-disney/public/images/original-icon.svg
  PROJECTS/clone-disney/public/images/play-icon-black.png
  PROJECTS/clone-disney/public/images/play-icon-white.png
  PROJECTS/clone-disney/public/images/search-icon.svg
  PROJECTS/clone-disney/public/images/series-icon.svg
  PROJECTS/clone-disney/public/images/slider-badag.jpg
  PROJECTS/clone-disney/public/images/slider-badging.jpg
  PROJECTS/clone-disney/public/images/slider-scale.jpg
  PROJECTS/clone-disney/public/images/slider-scales.jpg
  PROJECTS/clone-disney/public/images/viewers-disney.png
  PROJECTS/clone-disney/public/images/viewers-marvel.png
  PROJECTS/clone-disney/public/images/viewers-national.png
  PROJECTS/clone-disney/public/images/viewers-pixar.png
  PROJECTS/clone-disney/public/images/viewers-starwars.png
  PROJECTS/clone-disney/public/images/watchlist-icon.svg
  PROJECTS/clone-disney/public/index.html
  PROJECTS/clone-disney/public/logo192.png
  PROJECTS/clone-disney/public/logo512.png
  PROJECTS/clone-disney/public/manifest.json
  PROJECTS/clone-disney/public/robots.txt
  PROJECTS/clone-disney/public/videos/1564674844-disney.mp4
  PROJECTS/clone-disney/public/videos/1564676115-marvel.mp4
  PROJECTS/clone-disney/public/videos/1564676296-national-geographic.mp4
  PROJECTS/clone-disney/public/videos/1564676714-pixar.mp4
  PROJECTS/clone-disney/public/videos/1608229455-star-wars.mp4
  PROJECTS/clone-disney/src/App.css
  PROJECTS/clone-disney/src/App.js
  PROJECTS/clone-disney/src/components/Header.js
  PROJECTS/clone-disney/src/components/Home.js
  PROJECTS/clone-disney/src/components/Section.js
  PROJECTS/clone-disney/src/components/imgSlide.js
  PROJECTS/clone-disney/src/index.css
  PROJECTS/clone-disney/src/index.js
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#79 Made contributors cards to align horizontally
  contributor.html
Labels: hacktoberfest

#86 main to convert-react
  PROJECTS/Tic_Tac_Toe_by_VanillaJS/home.html
  PROJECTS/Tic_Tac_Toe_by_VanillaJS/script.js
  PROJECTS/Tic_Tac_Toe_by_VanillaJS/style.css
  assets/css/contributor.css
  contributor.html
Labels: hacktoberfest-accepted

#96 Added FAQ Page
  assets/css/faq.css
  assets/js/faq.js
  blog.html
  contributor.html
  faq.html
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted

#120 Projects page shows Real-Time data using Github API
  project.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#129 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: good first issue, hacktoberfest-accepted
